### ISSUE TITLE
Feature request: Disable data auto deletion & support data takeout/export

### ISSUE THREAD

**Issue by bentolor** [mueller-ma/PrepaidBalance#156]
Thanks for this nice idea and tool.

I wonder about the data deletion after 6 months? I failed to find an option to turn this off.

My use case: In my country you can deduct 20% of you phone bills if you used your phone (partially) for tax relevant purposes.

Prepaid Balance would help me, if I could
- collect & store my balance much longer and
- either export them in CSV to use excel to filter the topups or at least filter them to find out the dates and amounts of my balance topups.

Nota bene: My prepaid phone contract is charged every 28 days and most usage is included. Therefore my balance is mostly static in comparison to one charged per each call. 

Can we drop or allow to disable the autodeletion?

Thanks

**Comment by mueller-ma** [comment]
> I wonder about the data deletion after 6 months? I failed to find an option to turn this off.

The app loads all data and doesn't support paging (yet). I wanted to avoid performance issues caused by the missing paging and therefore I implemented the data deletion.

> Can we drop or allow to disable the autodeletion?

For now I can extend auto deletion to 2 years. In the future paging should be implemented and then the auto removal could be removed at all.

**Comment by bentolor** [comment]
Awesome @mueller-ma, Thanks! Looking forward to the next fdroid release!
