### ISSUE TITLE
Parse more data

### ISSUE THREAD

**Issue by wuniversales** [mueller-ma/PrepaidBalance#193]
My operator provides a lot of information about the current status of data, sms and minutes.

`Tu consumo adicional es de 0.00 euros. Te quedan 7.44 GB, 94 min nacionales y 998 SMS a DIGI, validos hasta dia 15.`

**Comment by panayotovip** [comment]
My operator have that respond:
```
Imate:
15:30:00 bezplatni minuti, do 12.06.2023
11.17 GBs DATA do 13.06.2023
```

An advanced option can be added where regex can be entered

Add 2 or more USSD codes to collect different information.

**Comment by sistein** [comment]
I would like to track my data consumption since my provider does not give those informations on the bill.

My text looks like this
=====
Ihr Tarif:  
o2 Free L Boost (LTE/5G).  
  
Ihre nächste Rechnung kommt in 27 Tagen. Ihr aktueller Verbrauch liegt bei 0 Min, 0 SMS einem Datenvolumen von 2821 MB
===== 

It would be great to log all these informations.
